# NOTE: 相対パスでインポートするとエラーが発生する
# https://stackoverflow.com/a/57789224
from auth.models.user import User
from auth.models.auth0_users import Auth0User
